version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:4.1.2-management
    container_name: rabbitmq-23441
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - red-central

  notificaciones-server:
    build: .
    container_name: notificaciones-server
    ports:
      - "8090:8090"
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: admin
      SPRING_RABBITMQ_PASSWORD: admin

      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/

      SPRING_DATASOURCE_URL: jdbc:postgresql://crdb-node1:26257,crdb-node2:26257,crdb-node3:26257/notificaciones_db?sslmode=disable&application_name=servicio-notificaciones
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:

    depends_on:
      - rabbitmq
    networks:
      - red-central

volumes:
  rabbitmq_data:

networks:
  red-central:
    external: true
