version: "3.8"

services:
  eureka-server:
    build: .
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - red-central
    environment:
      - SPRING_PROFILES_ACTIVE=default

networks:
  red-central:
    external: true
