server:
  port: 8000

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: publicaciones-autores
              uri: lb://api-publicaciones
              predicates:
                - Path=/autores,/autores/**
            - id: publicaciones-libros
              uri: lb://api-publicaciones
              predicates:
                - Path=/api/v1/libros/**
              filters:
                - StripPrefix=2
            - id: servicio-notificaciones
              uri: lb://servicio-notificaciones
              predicates:
                - Path=/api/v1/notificaciones/**
              filters:
                - StripPrefix=2

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.web: TRACE
