server:
  port: 8090  # Cambiado para puerto fijo y evitar problemas con Docker

spring:
  application:
    name: servicio-notificaciones
  datasource:
    #url: jdbc:postgresql://localhost:5432/notificaciones_db
    #username: postgres
    #password: admin123
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:26257/notificaciones_db?user=root&password=}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:admin}
    password: ${SPRING_RABBITMQ_PASSWORD:admin}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}
